CREATE DATABASE TheoryExamination
use TheoryExamination

CREATE TABLE Users(
	id INT,
	firstName VARCHAR(255),
	lastName VARCHAR(255),
	school VARCHAR(255),
	location VARCHAR(255),
	email VARCHAR(255),
	phoneNumber VARCHAR(255),
	dateOfBirth DATE,
	gender CHAR(1),
	CONSTRAINT userPK PRIMARY KEY(id),
	CONSTRAINT userGenderCheck CHECK(gender like 'B' or gender like 'G')
)

CREATE TABLE Pages (
	id INT,
	name VARCHAR(255),
	content VARCHAR(255),
	CONSTRAINT pagePK PRIMARY KEY(id)
)

CREATE TABLE PageLikes(
	UserId INT,
	PageId INT,
	CONSTRAINT pageLikesFKUser FOREIGN KEY(UserId) REFERENCES Users(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT pageLikesFKPage FOREIGN KEY(PageId) REFERENCES Pages(id) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE Friends (
	id INT,
	UserId INT,
	FriendId INT,
	CONSTRAINT friendsPK PRIMARY KEY(id),
	CONSTRAINT friendsFKUser FOREIGN KEY(UserId) REFERENCES Users(id) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE Posts (
	id INT,
	date DATE,
	content VARCHAR(255),
	UserId INT,
	CONSTRAINT postsPK PRIMARY KEY(id),
	CONSTRAINT postsFKUser FOREIGN KEY(UserId) REFERENCES Users(id) ON UPDATE NO ACTION ON DELETE NO ACTION
)

CREATE TABLE Comments (
	id INT,
	UserId INT,
	PostId INT,
	CONSTRAINT commentsPK PRIMARY KEY(id),
	CONSTRAINT commentsFKUser FOREIGN KEY(UserId) REFERENCES Users(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT comemntsFKPosts FOREIGN KEY(PostId) REFERENCES Posts(id) ON UPDATE NO ACTION ON DELETE NO ACTION
)


CREATE TABLE Shares(
	id INT,
	UserId INT,
	PostId INT,
	CONSTRAINT sharesPK PRIMARY KEY(id),
	CONSTRAINT sharesFKUser FOREIGN KEY(UserId) REFERENCES Users(id) ON UPDATE CASCADE ON DElETE CASCADE,
	CONSTRAINT sharesFKPost FOREIGN KEY(PostId) REFERENCES Posts(id) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE CommentLikes (
	UserId INT,
	CommentId INT,
	CONSTRAINT commentLikesFKUser FOREIGN KEY(UserId) REFERENCES Users(id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT commentLikesFKComment FOREIGN KEY(CommentId) REFERENCES Comments(id) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE Photos (
	id INT,
	imageContent VARCHAR(255),
	PostId INT,
	CONSTRAINT photosPK PRIMARY KEY(id),
	CONSTRAINT photosFKUser FOREIGN KEY(PostId) REFERENCES Posts(id) ON UPDATE CASCADE ON DElETE CASCADE,
)

CREATE TABLE Likes (
	PostId INT,
	UserId INT,
	CONSTRAINT likesFKPost FOREIGN KEY(PostId) REFERENCES Posts(id) ON UPDATE CASCADE ON DElETE CASCADE,
	CONSTRAINT likesFKUser FOREIGN KEY(UserId) REFERENCES Users(id) ON UPDATE CASCADE ON DELETE CASCADE
)